### ISSUE TITLE
1 million

### ISSUE THREAD

**Issue by saskra** [kmboehm/ForestMHC-data#1]
Thanks a lot for publishing the data! But these are not all of the one million peptides, are they?

**Comment by kmboehm** [comment]
No problem. Yes, that's right–there were ~1 million peptides collected from public data, and after filtering for length 9 and deconvolution by allele, there were ~1.6e5 uniquely assigned peptides with high confidence. That's the set here. More information about filtering and deconvolution is in the preprint.

**Comment by saskra** [comment]
This is a great source of positive examples for binding peptides per allele. But these data seem not to include negative examples of non-binding peptides per allele, do they? Did you use this kind of information for training your random forest?

**Comment by kmboehm** [comment]
Yes, these are only the positive (binding) examples because MS sampling of the immunopeptidome does not identify negatives. For negatives, we used decoy nonamers generated from SwissProt (see “Dataset and pre-processing” in the Methods section of the paper).
